// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pefbjlpcrurkrfyhbhct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlZmJqbHBjcnVya3JmeWhiaGN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NDQwMDQsImV4cCI6MjA3MjAyMDAwNH0.yePl9-40HWsELpLMcL9u7pJgtBJbzwoIS3uWIvjMH3A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});